### ISSUE TITLE
update Docker does not work

### ISSUE THREAD

**Issue by Iedjee** [ONLYOFFICE/Docker-CommunityServer#91]
I want to update my Docker-CommunityServer (with the Docker-DocumentServer) but I get an error /var/lib/rabbitmq not binded. I am on Ubuntu 16.04 LTS, latest Docker.

`~$ bash opensource-install.sh -u true -ims false

Select 'Y' to install ONLYOFFICE using Docker (recommended). Select 'N' to install it using RPM/DEB packages.
Please note, that in case you select RPM/DEB installation, you will need to manually install Mail Server and connect it to your ONLYOFFICE installation.
See instructions in our Help Center: http://helpcenter.onlyoffice.com/server/docker/mail/connect-mail-server-to-community-server-via-portal-settings.aspx

Install with Docker [Y/N/C]? Y

/var/lib/rabbitmq not binded`

The first time the new image of Documentserver (5.5.3.39) was downloaded, but I also got this error and the installation did not continue either. 
I dont have RabbitMQ installed and I dont know if i should have (never had and update always worked great).

Luckily the older version of DocumentServer keeps running on my Docker, but i would like to upgrade.

**Comment by Carazyda** [comment]
Hello @Iedjee Please delete and download our script again, we fixed this problem.

**Comment by Iedjee** [comment]
I still get the same error.
What i did:
`~$ wget https://download.onlyoffice.com/install/opensource-install.sh
--2020-06-01 13:37:08--  https://download.onlyoffice.com/install/opensource-install.sh
Herleiden van download.onlyoffice.com (download.onlyoffice.com)... 13.224.239.33, 13.224.239.129, 13.224.239.17, ...
Verbinding maken met download.onlyoffice.com (download.onlyoffice.com)|13.224.239.33|:443... verbonden.
HTTP-verzoek is verzonden; wachten op antwoord... 200 OK
Lengte: 3304 (3,2K) [application/x-sh]
Wordt opgeslagen als: ‘opensource-install.sh’

opensource-install.sh    100%[==================================>]   3,23K  --.-KB/s    in 0s

2020-06-01 13:37:08 (140 MB/s) - '‘opensource-install.sh’' opgeslagen [3304/3304]

~$ bash opensource-install.sh -u true -ims false
Select 'Y' to install ONLYOFFICE using Docker (recommended). Select 'N' to install it using RPM/DEB packages.
Please note, that in case you select RPM/DEB installation, you will need to manually install Mail Server and connect it to your ONLYOFFICE installation.
See instructions in our Help Center: http://helpcenter.onlyoffice.com/server/docker/mail/connect-mail-server-to-community-server-via-portal-settings.aspx
Install with Docker [Y/N/C]? Y
/var/lib/rabbitmq not binded`

I think the script is still the old, since the date is of 2017?
`
~$ ls -l
-rw-rw-r-- 1 xxxxx xxxxx 3304 dec 19  2017 opensource-install.sh
`

**Comment by Carazyda** [comment]
We updated the script, you can try now.

**Comment by Iedjee** [comment]
I did, and it is working now! Thank you for fixing the install/update script for this issue.

**Comment by t4nec0** [comment]
Hello,
is the `opensource-install.sh` unsupported now?
I installed onlyoffice/documentserver  version 5.4.2.46 with this script and wanted to upgrade.
If I try to get the script from https://download.onlyoffice.com/install/opensource-install.sh I get 

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>install/opensource-install.sh</Key>
<RequestId>294F7A4BE5F6D490</RequestId><HostId>AiKczOlsxP2pbib2j7wzR97KAPDc33sd+Uk8JvN6uTVJD+YOAh5iFJ96l5IuwEzNLMhKzKcyI+0=</HostId>
</Error>
```

I tried to update directly the container by pulling the `:latest` image but it didn't work. I got a lot of 
```
docker[7206]: nc: port number invalid:
gen 21 18:44:42 docs docker[7206]: Waiting for connection to the localhost host on port
```
in the container's log. I had to remove the image and retag the previous one as `:latest`

In fact, the documentation does not cite this script anymore...
https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx

So, how can I upgrade my OnlyOffice Document Server now?

**Comment by Carazyda** [comment]
Hello @t4nec0 If you want yo use script - try this https://download.onlyoffice.com/install/workspace-install.sh (in last release we renamed our products, and scripts too). 

For pulling docker image - you need to specify version. If you have any problem with install or update - please open a new issue in the right repository.
